version: '3.4'


networks:
  backend: #private
  frontend: #public

services:

  culturio-auth:
    image: culturio.auth
    build:
      context: .
      dockerfile: Span.Culturio.Auth/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;database=Culturio.Users;uid=sa; pwd=mTxuojqygYV_Gdwv3;"
    ports:
      - "5011:80"
    networks:
      - backend
    
    

  culturio-users:
    image: culturio.users
    build:
      context: .
      dockerfile: Span.Culturio.Microservices.Users/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;database=Culturio.Users;uid=sa; pwd=mTxuojqygYV_Gdwv3;"
    ports:
      - "5012:80"
    networks:
      - backend
    
    


  culturio-cultureobjects:
    image: culturio.cultureobjects
    build:
      context: .
      dockerfile: Span.Culturio.Microservices.CultureObjects/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;database=Culturio.CultureObjects;uid=sa; pwd=mTxuojqygYV_Gdwv3;"
    ports:
      - "5013:80"
    networks:
      - backend
    
    
  


  culturio-subscriptions:
    image: culturio.subscriptions
    build:
      context: .
      dockerfile: Span.Culturio.Microservices.Subscriptions/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;database=Culturio.Subscriptions;uid=sa; pwd=mTxuojqygYV_Gdwv3;"
      #- "Endpoints__Packages=http://culturio-packages/api/packages/"
      - "Endpoints__Packages=http://culturio-api/packages/" # ovo je VAZNO

    ports:
      - "5014:80"
    networks:
      - backend
    
    


  culturio-packages:
    image: culturio.packages
    build:
      context: .
      dockerfile: Span.Culturio.Microservices.Packages/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;database=Culturio.Packages;uid=sa; pwd=mTxuojqygYV_Gdwv3;"
    ports:
      - "5015:80"
    networks:
      - backend
    
 

  culturio-api:
    image: culturio.api
    build:
      context: .
      dockerfile: Span.Culturio.ApiGateway/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "Endpoints__Users=http://culturio-users/api/users"
      - "Endpoints__Subscriptions=http://culturio-subscriptions/api/subscriptions"
      - "Endpoints__Auth=http://culturio-auth/api/auth/"
      - "Endpoints__Packages=http://culturio-packages/api/packages/"
      - "Endpoints__CultureObjects=http://culturio-cultureobjects/api/cultureobjects/"

    ports:
      - "5002:80"
    networks:
      - backend
      - frontend
    depends_on:
      - culturio-users
      - culturio-auth
      - culturio-subscriptions
      - culturio-packages
      - culturio-cultureobjects


  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=y
    ports:
      - "5341:80"
    networks:
      - backend
      - frontend
    

