// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Span.Culturio.Microservices.Packages.Data;

#nullable disable

namespace Span.Culturio.Microservices.Packages.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221220224824_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Span.Culturio.Microservices.Packages.Data.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValidDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Package", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Muzeji",
                            ValidDays = 15
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kino",
                            ValidDays = 30
                        });
                });

            modelBuilder.Entity("Span.Culturio.Microservices.Packages.Data.Entities.PackageCultureObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AvailableVisits")
                        .HasColumnType("int");

                    b.Property<int>("CultureObjectId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageCultureObject", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableVisits = 3,
                            CultureObjectId = 1,
                            PackageId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableVisits = 5,
                            CultureObjectId = 2,
                            PackageId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvailableVisits = 2,
                            CultureObjectId = 3,
                            PackageId = 2
                        });
                });

            modelBuilder.Entity("Span.Culturio.Microservices.Packages.Data.Entities.PackageCultureObject", b =>
                {
                    b.HasOne("Span.Culturio.Microservices.Packages.Data.Entities.Package", "Package")
                        .WithMany("CultureObjects")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Span.Culturio.Microservices.Packages.Data.Entities.Package", b =>
                {
                    b.Navigation("CultureObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
