// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Span.Culturio.Microservices.Subscriptions.Data;

#nullable disable

namespace Span.Culturio.Microservices.Subscriptions.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221220224549_AddSeedData2")]
    partial class AddSeedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Span.Culturio.Microservices.Subscriptions.Data.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ActiveTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("RecordedVisits")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscription", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFrom = new DateTime(2022, 12, 20, 23, 45, 49, 126, DateTimeKind.Local).AddTicks(9960),
                            ActiveTo = new DateTime(2022, 12, 20, 23, 45, 49, 126, DateTimeKind.Local).AddTicks(9980),
                            Name = "sub package 1",
                            PackageId = 1,
                            RecordedVisits = 0,
                            State = "not active",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActiveFrom = new DateTime(2022, 12, 20, 23, 45, 49, 126, DateTimeKind.Local).AddTicks(9990),
                            ActiveTo = new DateTime(2022, 12, 20, 23, 45, 49, 126, DateTimeKind.Local).AddTicks(9990),
                            Name = "sub package 2",
                            PackageId = 2,
                            RecordedVisits = 0,
                            State = "not active",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Span.Culturio.Microservices.Subscriptions.Data.Entities.TrackVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CultureObjectId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEntered")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TrackVisit", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
